 User.delete_all
Category.delete_all

u1 = User.create(name:"Jane Sternbach", email:"janesternbach@gmail.com", password:"abc", password_confirmation:"abc", phone:"+16463275054", is_owner:true, address:"251 W 98th St, New York, NY")
u2 = User.create(name:"Jane Janerson", email:"janesternbach+1@gmail.com", password:"abc", password_confirmation:"abc", phone:"+16463275054", is_owner:false, address:"251 W 98th St, New York, NY")

c1 = Category.create(name:"Wine")
c2 = Category.create(name:"Whiskey")
c3 = Category.create(name:"Sports")
c4 = Category.create(name:"Nightclub")
c5 = Category.create(name:"Lounge")
c6 = Category.create(name:"Live Music")
c7 = Category.create(name:"Lesbian")
c8 = Category.create(name:"Latin")
c8 = Category.create(name:"Jazz")
c9 = Category.create(name:"Irish")
c10 = Category.create(name:"Hotel")
c11 = Category.create(name:"Sake/Soju")
c12 = Category.create(name:"Gay")
c13 = Category.create(name:"Dive")
c14 = Category.create(name:"College")
c15 = Category.create(name:"Karaoke")
c16 = Category.create(name:"Cigar")
c17 = Category.create(name:"Cabaret")
c18 = Category.create(name:"Beergarden")
c19 = Category.create(name:"Brewery")
c20 = Category.create(name:"Bowling Alley")
c21 = Category.create(name:"Billiards")
c22 = Category.create(name:"Hookah")
c23 = Category.create(name:"Outdoor Space")
c24 = Category.create(name:"Romantic")
c25 = Category.create(name:"Rooftop")
